name: Create PR from Dev to Int

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v0
        with:
          gh-version: 1.11.0

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] || [ "${{ github.event_name }}" == "push" ]; then
            gh pr create --base int --head dev --title "Merge Dev into Int" --body "Merge changes from Dev into Int."
          else
            echo "This workflow can only be triggered manually or on push to the dev branch."
            exit 1
          fi
